#!/bin/bash
# a symlink nvim -> . is needed
#  `:h startup` for details

WORKDIR="$(dirname "$(readlink -f "$0")")"

export XDG_CONFIG_HOME="$WORKDIR"

# hack: nvim config => $XDG_CONFIG_HOME/nvim
[ -L "$WORKDIR/nvim" ] || ln -sf . "$WORKDIR/nvim"

case "$1" in
	--update)
		cd "$WORKDIR" && exec ./install.sh --update
		;;
	--help | -h)
		"$WORKDIR/scripts/nvim" --help
		echo -e "\n---\nTry update pretty.nvim with \`nvim --update'"
		exit
		;;
esac

exec "$WORKDIR/scripts/nvim" "$@"
