#!/bin/bash
# a symlink nvim -> . is needed
#  `:h startup` for details

WORKDIR="$(readlink -f "$0" | xargs dirname)"

NVIM="$WORKDIR/prebuilts/nvim"

#export XDG_CONFIG_HOME="$WORKDIR"

# hack: nvim config => $XDG_CONFIG_HOME/nvim
#[ -L "$WORKDIR/nvim" ] || ln -sf . "$WORKDIR/nvim"

# 使用默认 XDG_CONFIG_HOME，避免在 WORKDIR 创建链接
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export NVIM_APPNAME="$(basename "$WORKDIR")"

test -L "$XDG_CONFIG_HOME/$NVIM_APPNAME" || ln -sf "$WORKDIR" "$XDG_CONFIG_HOME"

case "$1" in
    --update-plugins)
        exec "$NVIM" -c 'packloadall | silent! helptags ALL | UpdateRemotePlugins' +quit
        ;;
    --update*)
        cd "$WORKDIR" && exec ./install.sh "$@"
        ;;
    --help|-h)
        "$NVIM" --help

        cat <<EOF

---
Extend Options:
    --update                update pretty.nvim
    --update-core           update nvim binaries
    --update-plugins        update plugins' cache
EOF
        exit
        ;;
esac

export NVIM_REMOTE_SOCK="/tmp/nvim-$$.sock"

# 解决 clang-tidy 找不到标准头文件的问题
which xcrun >/dev/null && export CPATH="$(xcrun --show-sdk-path)/usr/include" || export CPATH=/usr/include

# listen on sock, required by lazygit
exec "$NVIM" --listen "$NVIM_REMOTE_SOCK" "$@"
