on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: https://git.mtdcy.top/actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Install
        run: |
          npm --version
          python3 --version
          MIRRORS=https://${{ vars.MIRRORS }} ./install.sh
        shell: bash

      - name: Verify
        run: |
          env
          set -x
          export PATH=/usr/local/bin:$PATH
          which nvim
          nvim -c 'exe "normal iHello World!\<Esc>" | wq' result.txt
          cat result.txt
          [ "$(cat result.txt)" = "Hello World!" ]
        shell: bash

      - name: Notify on failure
        if: failure()
        run: |
          curl --version
          curl -vL ${{ vars.NOTIFY_WEBHOOK }} \
              -H 'Content-Type: application/json' \
              --data @<(cat <<EOF
              {
                "token": "${{ secrets.NOTIFY_TOKEN }}",
                "title": "${{ github.repository }} ${{ job.status }}",
                "text":  "$(git show --abbrev-commit -s ${{ github.ref }} | sed 's/$/\\n/g')"
              }
          EOF
              )
        shell: bash
